### ISSUE TITLE
Is it possible to limit how many items are shown during the search ?

### ISSUE THREAD

**Issue by DavidBarishev** [quicoli/WPF-AutoComplete-TextBox#1]
I am using this wonderful auto complete textbox , and im wondering if there is a possibility to limit how many recommendations are shown ,because my list is pretty long  ,and as the user chooses , he is flooded with results . How can you limit the result (eg , say first 10) and the rest hidden , but accessible using the scrollbar ?

**Comment by quicoli** [comment]
Hi!

I'm checking on this this weekend.

thank you

2016-04-27 6:14 GMT-03:00 David Barishev <notifications@github.com>:

**Comment by quicoli** [comment]
Included a new property MaxPopupHeight. Setting this property, will
limit the popup height to the size you wish.
