### ISSUE TITLE
Add ability to include non-selectable rows

### ISSUE THREAD

**Issue by clawfrank** [quicoli/WPF-AutoComplete-TextBox#10]
It would be nice to add header and/or footer rows, e.g. an item that shows up at the start of the results that says "X results" or maybe section splitters, e.g.  categorize things by the first letter. They would have different formatting (this can be done now using the template selector), but more importantly, cannot be selected. I have spent a little time trying to do this myself in the ListBoxItem style in Generic.xaml, but have not been successful. Example:

```
<DataTrigger Binding="{Binding Content.IsEnabled}" Value="false">
    <Setter Property="Focusable" Value="False" />
</DataTrigger>

<Trigger SourceName="Content" Property="IsEnabled" Value="false">
    <Setter Property="Focusable" Value="False" />
</Trigger>
```

**Comment by quicoli** [comment]
I'll check this weekend
