### ISSUE TITLE
select inserted data instead suggested

### ISSUE THREAD

**Issue by juzamdjinn** [quicoli/WPF-AutoComplete-TextBox#17]
Hi,
it is possible to use input data instead suggested ?
Example :
i fill the searchbox container with animal objects ( complex objects ) , but i can search an animal not inserted in the collection and i would like to use it instead one in list  ( pressing enter i want that my input is used like other animal objects , a fake object because i insert only the name and not other info )  can you suggest a correct implementation ? ( i don't need to save the new animal in the list for future use , i need only to read these until i close the page ( xaml )

thank you

**Comment by quicoli** [comment]
Hi!

I believe you can bind the Text property to a ViewModel property and check
is this exists in the bound collection. So you handle what to do with it.

Regards,

**Comment by quicoli** [comment]
See the new Wiki. It shows how to add a new item to the list...
