### ISSUE TITLE
ISuggestionProvider async

### ISSUE THREAD

**Issue by bugproof** [quicoli/WPF-AutoComplete-TextBox#20]
why GetSuggestions is not async and you're creating a new thread instead of simply awaiting it?

https://github.com/quicoli/WPF-AutoComplete-TextBox/blob/80c9dd71da7f6cb31d0fdc02e321522a0d7ea498/AutoCompleteTextBox/AutoCompleteTextBox/Editors/AutoCompleteTextBox.cs#L480-L481

wouldn't it work if it was simply:

```csharp
IEnumerable list = await provider.GetSuggestions(searchText); 
```

I would like to make HTTP requests in GetSuggestions and naturally HTTP client methods would be called with `await`

I'd expect the interface to look like:

```csharp
public interface ISuggestionProvider
{
    Task<IEnumerable> GetSuggestions(string filter);
}
```

**Comment by quicoli** [comment]
Now we have .net core 3 I'll include this breaking change and release a new version for .net framework and .net core 3
