### ISSUE TITLE
Flicker when list changes

### ISSUE THREAD

**Issue by blakepell** [quicoli/WPF-AutoComplete-TextBox#21]
I'm currently using this as a command box in a mud client which is basically a tcp/ip app to a network server that is a text based game.  The auto complete box is at the bottom of the window and the Popup generally appears on top of that box.  My issue is, as the user types and the suggestion list gets smaller instead of the box shrinking it disappears totally and then re-appears where you get quarter second flicker (Where it's there, then not there, then there again).  I've tried various animations but they all feel jarring.  When the box doesn't shrink it still disappears and reappears when it would be visually ideal to have it stay in place while it's filtering (I realize that currently the ItemsSource gets reset with a new IEnumerable and it's not dealing with the same list which might have something to do with it).

Any thoughts on the best way to mitigate the disappear / reappear behavior?

**Comment by quicoli** [comment]
Hello!

Could you record the screen showing the behavior? I'm out for holidays
returning activities on January.

Merry Christmas and Happy New Year

**Comment by blakepell** [comment]
Thanks for the response.  Here's a GIF if the behavior.

![AutoCompleteBox](https://user-images.githubusercontent.com/5958430/71423094-e3d95180-2654-11ea-98c5-caac5f4d24cd.gif)

What this shows is the content under the popup briefly flickers (as the ListBox disappears from view and then re-appears with it's new items).

As an aside, I tested two avenues that both persisted the list instead of resetting the "ItemsSelector.ItemsSource".  The first route was using a CollectionView to filter the list and the second was putting an IsVisible property onto the item (that's implements INotifyProperty) and toggling that bool in "DisplaySuggestions" to hide/show items.  The interesting effect of both of those was the list didn't flicker if the ListBox was getting larger, but did if it was getting smaller.

**Comment by quicoli** [comment]
Hi,
This is open for a long time... It's this still happening in the latest version?
