### ISSUE TITLE
Setting Text after attaching to events

### ISSUE THREAD

**Issue by IRQ0x00** [quicoli/WPF-AutoComplete-TextBox#3]
Hi! Probably you can help me. I'm using original solution, but I see, you did not change this part. I'm talking about this in AutocompleteTextBox.cs:

```
            if (Editor != null)
            {
                if (SelectedItem != null)
                {
                    Editor.Text = BindingEvaluator.Evaluate(SelectedItem);
                }

                Editor.TextChanged += OnEditorTextChanged;
                Editor.PreviewKeyDown += OnEditorKeyDown;
                Editor.LostFocus += OnEditorLostFocus;

                //if (SelectedItem != null)
                //{
                //    Editor.Text = BindingEvaluator.Evaluate(SelectedItem);
                //}

            }
```

The problem is that now I'm using expanders, they ale collapsed when I open window that contains controls with these expanders. If I leave original code (it is commented) I get problems with expanders: if I expand some expander, autocomplete text boxes reset underlying bound property and suggest to select item one more time. It looks like expanding raises ApplyTemplte event, autocomplete changes Text and textchangedevent is rasied again. It resets selected item to null so I lose my property value. If I move setting Text before attaching to event handlers, there is no such problem. But I'm not sure it's the right way.

Also this problem occurs on already visible controls: sometimes if I open some window aith autocomeplte, it saves property value, but drops down itself and suggests me to select me my item again.

**Comment by quicoli** [comment]
Hi friend,

could please send me a little demo showing this situation? It would help me
a lot.

thank you.

2016-05-23 15:19 GMT-03:00 IRQ0x00 <notifications@github.com>:
