### ISSUE TITLE
Text binding: UpdateSourceTrigger=PropertyChanged does not work

### ISSUE THREAD

**Issue by dkoehler69** [quicoli/WPF-AutoComplete-TextBox#30]
The following type of binding does not work:

`Text="{Binding Foo, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"`

The view model is not notified whenever the property changes (ie when the text changes), but only when the AutoCompleteTextBox looses its focus. The later behavior should only apply when `UpdateSourceTrigger=LostFocus`.

**Comment by mitchcapper** [comment]
Dupe of #9
