### ISSUE TITLE
scrolling issues

### ISSUE THREAD

**Issue by julesx** [quicoli/WPF-AutoComplete-TextBox#37]
when you scroll the suggestions popup horizontally to the right (for example, to see text that is cut off), you are unable to scroll back left.

the Thumb tack is not visible in either the horizontal or vertical scrollbar.

**Comment by julesx** [comment]
i notice now that once you scroll horizontally, you are completely unable to dismiss the suggestions popup until you focus a completely different application window

**Comment by quicoli** [comment]
@julesx could you please try with this release 1.3.0
