### ISSUE TITLE
keyboard selection vs mouse selection

### ISSUE THREAD

**Issue by julesx** [quicoli/WPF-AutoComplete-TextBox#38]
With a databound autocomplete

`<autocompletetextbox:AutoCompleteTextBox SelectedItem="{Binding SelectedItem, Mode=TwoWay ... />`

if you type some letters, then use your mouse to select an entry, SelectedItem is set once.
if you type some letters, then use your arrow keys to navigate the suggestions popup and then pressing Enter OR Tab, SelectedItem is set twice

This causes some strange behavior when attempting to simultaneously bind to the Text property

**Comment by quicoli** [comment]
@julesx is this still happening?
