### ISSUE TITLE
Updating Text on selection from drop down

### ISSUE THREAD

**Issue by new-to-github** [quicoli/WPF-AutoComplete-TextBox#4]
Hi,

I'm have integrated your code in my demo app (thanks for that!!!) and it works seamlessly but i'm facing one issue. When i type something  for autocomplete and the suggestion list comes up, I'm not able to click and select anything from the list. I tried the same thing with your demo and the same thing happens, does it not work ?

Can you help me as to how I can solve this ?

**Comment by new-to-github** [comment]
Hi, Are you still supporting this project ?

**Comment by quicoli** [comment]
Hi, I'm sorry for taking so long to answer to you...  Is this happening only when using material design styles?

**Comment by sudolj** [comment]
I see what he is talking about.  Even using your demo it does not work.  If I start to type a state like New York.  Typing New shows all of the states that start with New.  If I try to select New York with the mouse click it does not select.  I can however select it by clicking the down arrow and selecting it.  The mouse button however does not allow selection in your example.
