### ISSUE TITLE
Never ending vertical scroll + disappearing scroll thumb

### ISSUE THREAD

**Issue by julesx** [quicoli/WPF-AutoComplete-TextBox#43]
When you have a large amount of suggestions, and you mouse over the scroll down thumb, it disappears.

If you then click the button that you cannot see, a continuous vertical scroll begins, as if the user was holding down the scroll down button.

**Comment by quicoli** [comment]
Posted this on stackoverflow, there you can see the reproduction of this issue: [see details](https://stackoverflow.com/questions/69595545/wpf-listbox-automatically-scrolls-to-first-or-last-element-when-clicking-on-the)

**Comment by julesx** [comment]
it would probably help if you posted some of the relevant code
no one is going to go dig through your entire code repo

**Comment by quicoli** [comment]
found a solution @julesx , will release later tonight. 👍

**Comment by quicoli** [comment]
Fixed in release 1.3.0
