### ISSUE TITLE
When clicking below scrollbar , the list scrolls to the end, then the list appears stuck

### ISSUE THREAD

**Issue by QM-OSchwab** [quicoli/WPF-AutoComplete-TextBox#49]
When I click on the area below the scrollbar button, the list scrolls automatically to the end , then the scrollbar and the list is stuck. When typing in the textbox, it hides the list, then everything works fine again : 

![Demo](https://user-images.githubusercontent.com/51437516/148022591-e71c3d6e-778f-4895-a00a-16c621288411.gif)

**Comment by quicoli** [comment]
I'm investigating that... it seems to be a WPF bug.

**Comment by quicoli** [comment]
Found a solution..... I'm releasing later tonight.

**Comment by QM-OSchwab** [comment]
Wow that was fast !  Congrats !

**Comment by quicoli** [comment]
Fixed on release 1.3.0
