### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Jsasnauskas** [quicoli/WPF-AutoComplete-TextBox#5]
Hi, I have found similar project on https://wpfautocomplete.codeplex.com/ under license of Ms-PL. 
Is it compatible with Mit License that you are providing?

**Comment by quicoli** [comment]
Hi @Jsasnauskas I've noticed the original programmer, and he didnt say anything. Maybe he's not supporting his version anymore. If you take a look at https://www.codeproject.com/Tips/801004/WPF-AutoComplete-TextBox you see he has distributed the code using other license.  So I don't know if he cares so much about that....
