### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by rrFK** [quicoli/WPF-AutoComplete-TextBox#55]
If the items for the AutoCompleteTextBox are loaded from a database, a System.NullReferenceException is thrown in the GetSuggestions(string filter) method after typing a character into the text box. In the lambda expression, x is null.

Here is the full method:
public IEnumerable GetSuggestions(string filter)
{
	return items.Where(x => x.Contains(filter));
}

**Comment by quicoli** [comment]
Hi
Have you found a solution?

I believe this is happening because you might have a null value in the database, that's not related to this control but to Linq itself.

You could rewrite your query like

items.Where(x => x!= null && x.Contains(filter));
