### ISSUE TITLE
Dynamic data in provider

### ISSUE THREAD

**Issue by melsawy93** [quicoli/WPF-AutoComplete-TextBox#56]
Hi, I am trying to have a combobox column with an autocomplete and filter feature. I stumbled upon this tool on stackoverflow and I am attempting to use it. (I am new to WPF/C#/Coding)

Does this tool allow for a dynamic list/observablecollection in my provider class? I looked at sample code for the Simple Demo and noticed the lists are readonly.

What I am trying to achieve in terms of a simple format -> I have Customer objects and list of items. Each customer has a name and an item (as a property). Each item only has a name property. In my datagrid I have a text column and a combobox column that shows the item that the customer has. The idea is that no customers can have duplicate items so ideally the combobox for a given cell will contain the list of all items available minus the items in other customers. This way my autocomplete and combobox will not show any duplicate "taken" item. This means my provider will be updated each time I click a cell (via events).

Thank you!

**Comment by quicoli** [comment]
Hi

Probably you have found a solution for this already. Your problem is more related to design than the control itself.
I added a wiki showing how to add an item to the observable collection, so you can update it.

I hope this gives you an idea of design.
