### ISSUE TITLE
MouseEvent with ItemTemplate

### ISSUE THREAD

**Issue by CedrickLemay** [quicoli/WPF-AutoComplete-TextBox#60]
Is it normal that the Datatemplatr wont fire mouse events?

**Comment by quicoli** [comment]
Hi @CedrickLemay,

I think I didn't understand your question very well. What is your context/scenario?
Are you creating a custom `DataTemplate`? 

For more info related to DataTemplate see this [article](https://www.codemag.com/article/0907111/Dressing-Up-Your-Data-with-WPF-DataTemplates)

👍🏻

**Comment by CedrickLemay** [comment]
I just saw that you handle the **PreviewMouseDown** event, which explain why when i add a **MouseDown** event to the **WebColorItemTemplate** DataTemplate won't work. So to answer my own question, seems like it's normal

**Comment by CedrickLemay** [comment]
KeyDown does work on the other hand, but because anymouse event is automatically Handled, i can't add any event to the control related to the mouse pressing.

**Comment by quicoli** [comment]
Sorry for asking @CedrickLemay , the use of a MouseDown event looks very particular to your scenario... would mind to share what you are trying to accomplish?

**Comment by CedrickLemay** [comment]
I am trying to make an event happen upon selection of an item. I was adapting from the SelectedItem causing problem (in, i think, another version of this AutoCompleteTextBox, by someone else) when the binded property was changed, since it was triggered when the window was loaded. Limiting it to the mousedown and keydown did the work. Now only keydown works sinc the Enter Key is not Handled.

**Comment by quicoli** [comment]
Hi,

Have you see the simple demo  from the source code? There you can see how to track the selected item properly for extra actions but I think this is more a view model responsability than the control itself.

👍

________________________________
