### ISSUE TITLE
Display specific member out of object in listed suggestions

### ISSUE THREAD

**Issue by muathalbolushi** [quicoli/WPF-AutoComplete-TextBox#62]
HELP WANTED..

I can see there is a properties with name "DisplayMember" which takes effect after the selection done, but I wonder if there is an option to select specific member out of the object in the listed suggestions.

![Screenshot 2023-08-08 203842](https://github.com/quicoli/WPF-AutoComplete-TextBox/assets/26137539/28050d34-e3bf-4c4a-8976-5ca88a455436)

many thanks.

**Comment by muathalbolushi** [comment]
solved using
`override string ToString()`

**Comment by quicoli** [comment]
Hi!

Remember, WPF is very powerful for data display, you can use DataTemplate to show data the way you need 👍

________________________________
