### ISSUE TITLE
Question: Usage and Autocomplete

### ISSUE THREAD

**Issue by LeviGNMBS** [quicoli/WPF-AutoComplete-TextBox#69]
Hi,

Im trying to use your control to provide some autocompletion to a terminal style project. The sample projects got me started but tbh i don't find them very clear. Is there a wiki somewhere explaining all the functions?

First question: I can't seem to get the control to show suggestions when nothing is entered? The provider isn't even queried at that point which is weird since i would suspect that choice to be a part of the provider rather than the control?

Secondly, if i press the arrow keys the box pops up even if no suggestions (empty enumerable) are given by the provider? Is that a bug?

And lastly is there a way to add history functionality? i tried to do this myself but since the box grabs the arrow events, i can't seem to trigger on the alt+arrow or similar events to implement history.

**Comment by quicoli** [comment]
Hi,

>> Im trying to use your control to provide some autocompletion to a terminal style project. The sample projects got me started >> but tbh i don't find them very clear. Is there a wiki somewhere explaining all the functions?

I don't have a wiki explaining everything. I have only this:
[How to add a new item](https://github.com/quicoli/WPF-AutoComplete-TextBox/wiki/How-to-add-a-new-item-to-a-list%3F).
There's no extensive functionality in this control. It's purpose is to provide an auto-complete as you type, based in the control content (text) and the implemented suggestion provider. 

>>First question: I can't seem to get the control to show suggestions when nothing is entered? The provider isn't even queried >>at that point which is weird since i would suspect that choice to be a part of the provider rather than the control?

At the moment the SuggestionProvider is only invoked and there's text in the TextBox. A workaround for you would be to type a space and handle that space in you SuggestionProvider implementation.

>>Secondly, if i press the arrow keys the box pops up even if no suggestions (empty enumerable) are given by the provider? Is >>that a bug?

🤔 it might be a bug, I might investigate this later.

>>And lastly is there a way to add history functionality?

If you need an item to be displayed as "history" it has to be added to the suggestion provider list and implement some logic to avoid duplicated content. The mentioned WIKI shows how to add an item, you might think in something similar.


I hope this helps you.
