### ISSUE TITLE
Binding to the text property with UpdateSourceTrigger=PropertyChanged doesn't work

### ISSUE THREAD

**Issue by mitchcapper** [quicoli/WPF-AutoComplete-TextBox#9]
So one solution would be to change the xaml to 
```
<TextBox x:Name="PART_Editor"
                                             HorizontalAlignment="Stretch"
                                             VerticalAlignment="Center"
                                             Style="{StaticResource ResourceKey=TransparentTextBoxStyle}"
                                             Text="{Binding Path=Text, RelativeSource={RelativeSource Mode=TemplatedParent}, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" />
```
This would have a very minor performance hit, however clearly no one is relying on this property currently.  I would like if it could somehow automatically use the right one or be a user preference.  I think we could do the user preference by adding another parameter on the AutoCompleteTextBox of "UpdateTextExplicitly" and then manually establish the binding in code behind rather than in xaml.

I figured open an issue for discussion.

**Comment by quicoli** [comment]
Hi @mitchcapper 
I don't if I understood... you are suggesting that for situations where user doesn't use MVVM?

**Comment by mitchcapper** [comment]
It is where a user may want to use for beyond just auto complete.  For example I allow the user to pick from  the auto complete list or type their own.   If someone binds to the VM with PropertyChanged source trigger for the Text value on a normal textbox as the user type its updates the VM.  On this one it would not, effectively the PropertyChanged trigger does not work (as the binding the control uses is not).

**Comment by quicoli** [comment]
@mitchcapper I did something like that. My user could pick from the list or type one of their own:

```
 <editors:AutoCompleteTextBox HorizontalAlignment="Left" 
        Text="{Binding CustomChoice, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged, ValidatesOnDataErrors=True}"
        Style="{StaticResource MaterialAutoCompleteTextBox}"
        MaxLength="200"              
        CharacterCasing="Upper"
        x:Name="autoCompleteChoices"                         
        DisplayMember="Choice"
        Height="30"
        Width="800"
        Provider="{StaticResource ChoicesSuggestionProvider}"
        ItemTemplate="{StaticResource ResourceKey=choiceTemplate}">
        <editors:AutoCompleteTextBox.SelectedItem>
                   <Binding Path="SelectedChoice" Mode="TwoWay" UpdateSourceTrigger="PropertyChanged"/>
        </editors:AutoCompleteTextBox.SelectedItem>
        <editors:AutoCompleteTextBox.LoadingContent>
                          <TextBlock Text="Loading..." Margin="5" FontSize="14" />
        </editors:AutoCompleteTextBox.LoadingContent>
</editors:AutoCompleteTextBox>
```
CustomChoice is a string property in my ViewModel and I have other, SelectedChoice (my business object. When user types in the control, typing something new, my SelectedChoice is null, but my CustomChoice has the typed text, so I know when user didn't picked an item up from the list...

**Comment by mitchcapper** [comment]
@quicoli Thanks!  So in your example you bind to CustomChoice to the Text property with `UpdateSourceTrigger=PropertyChanged` however that trigger doesn't do anything as in the xaml we only bind the actual textbox to the Text property using the default source trigger (focus lost): https://github.com/quicoli/WPF-AutoComplete-TextBox/blob/master/WpfControls/WpfControls.CS/Editors/Themes/Generic.xaml#L91

**Comment by quicoli** [comment]
I see...  Give a try please, I remember of that working properly

See you

**Comment by mitchcapper** [comment]
@quicoli  maybe you notice if you arrow up and down on the list that gets update but with PropertyChanged as the user types a letter the VM should get the property updated.  I have tried and it is not working for me (and with that XAML it makes sense).  Add a debug.writeline to your VM to see if the property is actually updating with each letter?

**Comment by quicoli** [comment]
I'm far from computer now, What you think if we set updatesourcetrigger =
TemplatedParent

Is that possible?

**Comment by mitchcapper** [comment]
I wish:)  As far as I know we cannot have the binding mirror the parent.  Some googling has others with custom user controls having the same issue.  I see we have 3 options:
1) Change the xaml we have to always do propertychanged, a minor performance hit occurs all we are doing is updated the backend value however so performance hit should be extremely negligible (https://stackoverflow.com/questions/6532383/textbox-updatesourcetrigger-propertychanged-does-it-really-affect-performanc?rq=1).   As long as the user doesn't change their code to also update on PropertyChanged their code will not have the binding called any more often.
2) We add another property to the control like UpdateTextOnPropertyChanged and then bind the xaml to the class in code behind, this way the user has full control on if we are binding in
3) We do nothing, people already use the control without issue and I can use some View hacking to get around the problem for myself.

Personally I think performance wise it would be fairly minor to do item 1 but let me know the preferred call and I can do a PR.

**Comment by quicoli** [comment]
Go on with option 2, so user can choice what is better.. Agree?

**Comment by afzal646** [comment]
Is there any way to react in code to when a user has actually selected an item? So an event such as SelectionChanged or SelectedItemChanged?
--

**Comment by kaushikamcs** [comment]
@mitchcapper , I am actually facing the exact issue. I have another button in my view and want to enable the button if there are 3 or more characters entered in the textbox. Now, I have a Command to the button which enables on the said scenario. However, until I tab off, the my CustomChoice is not getting set.

Can you please tell me if you were able implement option 1 which you have mentioned in one of the comments?

Generic.xaml:
 ` <TextBox x:Name="PART_Editor"
                                             HorizontalAlignment="Stretch"
                                             VerticalAlignment="Center"
											 Foreground="{Binding Path=Foreground, RelativeSource={RelativeSource Mode=TemplatedParent}, Mode=OneWay}"
                                             Style="{StaticResource ResourceKey=TransparentTextBoxStyle}"
                                             Text="{Binding Path=Text, RelativeSource={RelativeSource Mode=TemplatedParent}, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" />`


MyViewModel.xaml:

`<editors:AutoCompleteTextBox HorizontalAlignment="Left"
                                                 Text="{Binding Path=CustomChoice, UpdateSourceTrigger=PropertyChanged, Mode=TwoWay}" 
                                                 Style="{StaticResource MaterialAutoCompleteTextBox}"
                                                 MaxLength="50"                         
                                                 CharacterCasing="Upper"
                                                 DisplayMember="Name"
                                                 Height="26"
                                                 Width="450"
                                                 Provider="{StaticResource ResourceKey=StateSuggestionProvider}"
                                                 ItemTemplate="{StaticResource ResourceKey=StateTemplate}">
              <editors:AutoCompleteTextBox.SelectedItem>
                <Binding Path="SelectedState" Mode="TwoWay" UpdateSourceTrigger="PropertyChanged" ValidatesOnDataErrors="True">
                </Binding>
              </editors:AutoCompleteTextBox.SelectedItem>
              <editors:AutoCompleteTextBox.LoadingContent>
                <TextBlock Text="Loading..." Margin="5" FontSize="14" />
              </editors:AutoCompleteTextBox.LoadingContent>
            </editors:AutoCompleteTextBox>
`

Appreciate you help

**Comment by quicoli** [comment]
Hi, could you provide me a demo of your app, showcasing what you need?

**Comment by kaushikamcs** [comment]
![SampleAutoCompleteApp](https://user-images.githubusercontent.com/34301409/54903131-3092cf00-4f01-11e9-8c15-fac41c1f7629.gif)

I have provided a gif recording of the issue. I have a Search button which should get enabled as and when user types text on the auto complete box. 

[WPF-AutoComplete-TextBox-Modified.zip](https://github.com/quicoli/WPF-AutoComplete-TextBox/files/3002082/WPF-AutoComplete-TextBox-Modified.zip)
Now I have modified to set Text property when the Edirot Text changes. But is that the only way to overcome the problem?

**Comment by aivarasatk** [comment]
As far as I understand this still isn't fixed?
For me binding to Text with UpdateSourceTrigger=PropertyChanged does not send updates, this property is updated only when something from the drop down is selected. HOWEVER the SelectedItem fires updates for each entered character BUT the value is always null unless you select something from the dropdown.

**Comment by matosjr** [comment]
> I wish:) As far as I know we cannot have the binding mirror the parent. Some googling has others with custom user controls having the same issue. I see we have 3 options:
> 
> 1. Change the xaml we have to always do propertychanged, a minor performance hit occurs all we are doing is updated the backend value however so performance hit should be extremely negligible (https://stackoverflow.com/questions/6532383/textbox-updatesourcetrigger-propertychanged-does-it-really-affect-performanc?rq=1).   As long as the user doesn't change their code to also update on PropertyChanged their code will not have the binding called any more often.
> 2. We add another property to the control like UpdateTextOnPropertyChanged and then bind the xaml to the class in code behind, this way the user has full control on if we are binding in
> 3. We do nothing, people already use the control without issue and I can use some View hacking to get around the problem for myself.
> 
> Personally I think performance wise it would be fairly minor to do item 1 but let me know the preferred call and I can do a PR.

`<TextBox x:Name="PART_Editor"
                                             HorizontalAlignment="Stretch"
                                             VerticalAlignment="Center"
                                             Style="{StaticResource ResourceKey=TransparentTextBoxStyle}"
                                             Text="{Binding Path=Text, RelativeSource={RelativeSource Mode=TemplatedParent}, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" />`

I suspect the problem is that `Text="{Binding Path=Text, ...` is trying to bind `TextBox.Text` to a property in your ViewModel, instead of the ` AutoCompleteTexBox.Text`, it was for me in a different solution. It is worth to check. If not, another problem is that if inside AutoCompleteTexBox.cs you assign values direct to `TextBox.Text` by doing something like `_tb.Text = "something"`, it won't work. What I did was use `this.Text = "something"` instead.
